### ISSUE TITLE
Issues in P2P scenarios between NET > NS2 project references due to assembly naming

### ISSUE THREAD

**Issue by kzu** [lovettchris/SgmlReader#11]
Consider this scenario: App.csproj (NET4x/NET5), references Common.csproj (NS2/2.1)

The current package uses assembly (file) name SgmlReaderCore.dll in Common.csproj, but in App.proj, it's SgmlReaderDll.dll. This means that when copying dependencies to the output of App, only the latter will be copied, and code in Common.dll that attempts to use SgmlReader (which will have been compiled against SgmlReaderCore dll) will fail with a file not found error.

Here is a solution that reproduces the issue:

[App.zip](https://github.com/lovettchris/SgmlReader/files/6355341/App.zip)

(NOTE: this most likely isn't limited to project to project references, and would also happen for any nuget package that ships NS assemblies and is consumed in non-NS projects)

**Workaround**: 

* Add a `GeneratePathProperty=true` to the package reference:

```xml
    <PackageReference Include="Microsoft.Xml.SgmlReader" Version="1.8.21" GeneratePathProperty="true" />
```

* Then include the renamed dll in the output:

```xml
  <ItemGroup>
    <None Include="$(PkgMicrosoft_Xml_SgmlReader)\lib\netstandard2.0\SgmlReaderCore.dll" CopyToOutputDirectory="PreserveNewest" Visible="false" />
    <None Include="$(PkgMicrosoft_Xml_SgmlReader)\lib\netstandard2.0\SgmlReaderCore.pdb" CopyToOutputDirectory="PreserveNewest" Visible="false" />
  </ItemGroup>
```

**Comment by daiplusplus** [comment]
I've got a new PR that unifies things back into a single `.csproj` - no more `Core` and `Dll` projects btw: https://github.com/lovettchris/SgmlReader/pull/21

**Comment by lovettchris** [comment]
I believe this is now fixed, it is now uniformly named `SgmlReaderDll.dll` and this name is chosen on purpose so as not to conflict with the CLI named `SgmlReader.exe` which on .NET core platforms also has a CLI assembly named `SgmlReader.dll`.  So the "library" that you include in your app is named `SgmlReaderDll.dll`.
