### ISSUE TITLE
SgmlDtd.Parse fails to read OFX 1.6 DTD

### ISSUE THREAD

**Issue by daiplusplus** [lovettchris/SgmlReader#13]
[The `ofx160.dtd` file is attached to this post](https://github.com/lovettchris/SgmlReader/files/6661747/ofx160.dtd.txt) (renamed with `.txt` extension as GitHub does not allow `.dtd` file extensions to be uploaded as issue attachments).

The OFX 1.6 DTD is also available here: https://www.ofx.net/downloads.html (inside the Version 1.6 zip).

I'm using `Microsoft.Xml.SgmlReader` version `1.8.21` to try to parse it:

```
using( FileStream fs = new FileStream( @"OFX1.6\ofx160.dtd", FileMode.Open, FileAccess.Read, FileShare.Read, bufferSize: 4096 ) )
using( StreamReader rdr = new StreamReader( fs ) )
{
    SgmlDtd dtd = SgmlDtd.Parse(
        baseUri : null,
        name    : "OFX",
        input   : rdr,
        subset  : "",
        nt      : new NameTable(),
        resolver: new DesktopEntityResolver()
    );

    return dtd;
}
```

However it fails with this exception:

> Invalid declaration '`<!DOCTYPE`'.  Expecting 'ENTITY', 'ELEMENT' or 'ATTLIST'.  
> Referenced on line 1, position 11 of internal entity 'OFX'

Stack trace:

```
   at Sgml.SgmlDtd.Parse(Uri baseUri, String name, TextReader input, String subset, XmlNameTable nt, IEntityResolver resolver)
   at MyProgram.ReadOfxSgmlDtd() 
```

-------------------

The `ofx160.dtd` starts like this:

```
<!DOCTYPE OFX [

<!--#version 160 -->

<!--
    $Revision:   1.0  $
    $Date:   28 Sep 1999 10:50:36  $
       
 Open Financial Exchange DTD 
 Copyright 1997, 1998, 1999 CheckFree Corp., Intuit Inc., Microsoft Corp.
 All rights reserved

-->
```

Given that the SgmlReader's own project description says it's "handy" for processing SGML like OFX _specifically_ then this issue seems particularly embarrassing...

![image](https://user-images.githubusercontent.com/1693078/122191252-6bb5ab80-ce47-11eb-9e32-b29a4b859149.png)

**Comment by lovettchris** [comment]
I see, well technically the "DTD" is the part inside the `<!DOCTYPE` element, so if you unwrap that DOCTYPE by removing `<!DOCTYPE OFX [` and the terminating `]>` then the resulting OFX DTD should load properly, have you tried that?

**Comment by daiplusplus** [comment]
@lovettchris  Hurrah! Yes, that worked. Thank you!

One problem though: SgmlReader seems to be adding a trailing `\r\n` to the end of every `XmlElement.InnerText` and Text-node's `.Value` - I tried different values for `WhitespaceHandling` but it had no effect.

**Comment by lovettchris** [comment]
Ok, great.  The newlines being included in node text is probably by design for now, I don't think SgmlReader has an option to strip that from the text.  So the string Trim() method will be required.

**Comment by daiplusplus** [comment]
That's unfortunate.

I'll add a feature-request for that then :)
