### ISSUE TITLE
Feature suggestion: SgmlDtd.Parse should consume any outer `<!DOCTYPE` and `]>`.

### ISSUE THREAD

**Issue by daiplusplus** [lovettchris/SgmlReader#14]
From https://github.com/lovettchris/SgmlReader/issues/13

The `SgmlDtd.Parse()` method should detect if the `TextReader input` starts at a `<!DOCTYPE` token, and if so, consume it - then read the rest of the DTD body, and then consume the trailing `]>` if it started with  `<!DOCTYPE`.

**Comment by lovettchris** [comment]
is now fixed in 1.8.24

**Comment by daiplusplus** [comment]
Oooh, thanks! Saves me the trouble :)

**Comment by lovettchris** [comment]
cool, hope it works  :-) Let me know if you find any bugs, thanks.
