### ISSUE TITLE
Feature suggestion: SgmlReader should have an option to configure automatic insertion of trailing \r\n to InnerText/Value.

### ISSUE THREAD

**Issue by daiplusplus** [lovettchris/SgmlReader#15]
From https://github.com/lovettchris/SgmlReader/issues/13

Currently `SgmlReader` always inserts a trailing `\r\n` when reading the `.Value` and `.TextContent` of an `XmlNode`. I don't think this is _correct_ behaviour already (but @lovettchris say's it's By Design, so this isn't a bug-report), but this does cause issues with other programs/libraries that accept `XmlDocument`/`XmlNode` graphs that don't expect trailing whitespace, and the workaround to add `.Trim()` everywhere is a pain - as well as causing extraneous GC allocatations.

**Comment by daiplusplus** [comment]
I was running the existing tests in the solution and I saw that the HTML tests _don't_ cause trailing linebreaks to be rendered to the output. I spent a good amount of time going through the project but I can't understand where the trailing line-breaks are coming from...

**Comment by lovettchris** [comment]
If you can share one of your OFX files I can take a look.  Just strip out any confidential info first, thanks.

**Comment by daiplusplus** [comment]
@lovettchris Sure - I'm just using the test `.ofx` files from `OfxSharp`, for example:  https://github.com/Jehoel/OFXSharp/blob/master/source/OfxSharp.NETCore.Tests/Files/bradesco.ofx

You'll need to strip the `OFXHEADER` lines, ofc.

**Comment by daiplusplus** [comment]
@lovettchris I recognize it was a bit improper of me not to provide a full minimum-reproduction.

You can copy+paste this into Linqpad 6 (after adding a NuGet reference to `Microsoft.Xml.SgmlReader` `1.8.21`) and run it and it will reproduce the issue:

```
const String bradescoOfxFileUri    = @"https://raw.githubusercontent.com/Jehoel/OFXSharp/master/source/OfxSharp.NETCore.Tests/Files/bradesco.ofx";
const String ofx160DtdUri          = @"https://raw.githubusercontent.com/Jehoel/OFXSharp/master/source/Specifications/OFX1.6/ofx160.dtd";
//const String ofx160DtdTrimmedUri = @"https://raw.githubusercontent.com/Jehoel/OFXSharp/master/source/Specifications/OFX1.6/ofx160.trimmed.dtd";

async Task Main()
{
	String bradescoOfxText = await GetTextAsync( bradescoOfxFileUri, trimUntil: "<OFX>", trimAfter: null );
	String ofx160Dtd       = await GetTextAsync( ofx160DtdUri      , trimUntil: "<!--#", trimAfter: "]>" );
	
	XmlDocument asXml = ConvertSgmlToXml( ofx160Dtd, bradescoOfxText );
	//asXml.Dump();
	
	XmlNode codeNode = asXml.SelectSingleNode("//*[local-name()='CODE']");
	String sonrsStatusCodeInnerText = codeNode.InnerText;
	
	if( sonrsStatusCodeInnerText.EndsWith("\r\n") )
	{
		"Beep-boop! Erroneous trailing line-break detected!".Dump();
	}
	else
	{
		"Working as intended.".Dump();
	}
}

private static async Task<String> GetTextAsync( String url, String? trimUntil, String? trimAfter )
{
	HttpClient httpClient = new HttpClient();
	using( HttpResponseMessage resp = await httpClient.GetAsync( url ) )
	{
		String body = await resp.Content.ReadAsStringAsync();
		
		_ = resp.EnsureSuccessStatusCode();
		
		if( trimUntil != null )
		{
			Int32 idx = body.IndexOf( trimUntil );
			if( idx < 0 ) throw new InvalidOperationException( "Couldn't find \"" + trimUntil + "\" in response." );
			body = body.Substring( startIndex: idx );
		}
		
		if( trimAfter != null )
		{
			Int32 idx = body.LastIndexOf( trimAfter );
			if( idx < 0 ) throw new InvalidOperationException( "Couldn't find \"" + trimAfter + "\" in response." );
			body = body.Substring( startIndex: 0, length: idx );
		}
		
		return body;
	}
}

private static XmlDocument ConvertSgmlToXml( String ofxSgmlDtdText, String sgmlText )
{
	using( StringReader rdr = new StringReader( sgmlText ) )
	{
		return ConvertSgmlToXml( ofxSgmlDtdText, rdr );
	}
}

private static XmlDocument ConvertSgmlToXml( String ofxSgmlDtdText, TextReader reader )
{
    SgmlDtd ofxSgmlDtd = ReadOfxSgmlDtd( ofxSgmlDtdText );

    SgmlReader sgmlReader = new SgmlReader();
    sgmlReader.WhitespaceHandling = WhitespaceHandling.None;
    sgmlReader.InputStream        = reader;
    sgmlReader.DocType            = "OFX";
    sgmlReader.Dtd                = ofxSgmlDtd;

    XmlDocument doc = new XmlDocument(); 
    using( XmlWriter xmlWriter = doc.CreateNavigator().AppendChild() ) 
    { 
        while( !sgmlReader.EOF )
        {
            xmlWriter.WriteNode( sgmlReader, defattr: true );
        }
    }
    
    return doc;
}

private static SgmlDtd ReadOfxSgmlDtd( String ofxSgmlDtdText )
{
    using( StringReader dtdReader = new StringReader( ofxSgmlDtdText ) )
    {
        SgmlDtd dtd = SgmlDtd.Parse(
            baseUri : null,
            name    : "OFX",
            input   : dtdReader,
            subset  : "",
            nt      : new NameTable(),
            resolver: new DesktopEntityResolver()
        );

        return dtd;
    }
}
```

**Comment by lovettchris** [comment]
Thanks for the repro, test 02.test was showing the same behavior for HTML but I added a new test to make this more clear.  See test [62.test](https://github.com/lovettchris/SgmlReader/blob/master/SgmlTests/Resources/62.test).  The whitespace you are talking about is adjacent to text content and the [XML specification](https://www.w3.org/TR/REC-xml/) calls this "significant whitespace" and demands that _An XML processor must always pass all characters in a document that are not markup through to the application_ and this is what is happening with SgmlReader.  The SgmlReader cannot know the whitespace is not important in the OFX case without having deeper knowledge of the OFX spec, which the SgmlReader does not have.  Only your application has that knowledge.  The following HTML example shows why this whitespace is important:
```xml
<p>more
<b>important
</b><i>information</p>
```
If the whitespace was stripped from the end of these words you would end up with the incorrect html:

more**important**_information_

losing the fact that these were meant to be separate words.

**Comment by daiplusplus** [comment]
Would you be open to me submitting a PR that added the ability to override the handling of whitespace? Or should this issue be closed?

**Comment by lovettchris** [comment]
I'm open to it, some sort of `bool TrimWhitespace {get; set;}` option perhaps?

**Comment by lovettchris** [comment]
(separate from the XmlReader WhitespaceHandling flag - since WhitespaceHandling  has a different meaning).

**Comment by daiplusplus** [comment]
BTW @lovettchris are you okay with my PR adding an `.editorconfig` to the solution?

Also, as far as I can tell, the entire solution is using `\n` instead of `\r\n`, is that correct? I keep getting tripped-up by git's `autocrlf` so I always turn it off.

**Comment by daiplusplus** [comment]
@lovettchris Here's my first-draft - I did iterate on the design, you can see my earlier approach in ec15a690712b5382dcea6992e4457730edf3dcb4 but I changed it to a flags-enum for greater flexibility in 6ac1f4983ae77c55249c558e602dd2e4d3624f62 - subsequent commits are just updates and clean-up.

I don't intend for this to be merged right-away as more tests can be added - I wanted to ensure you're okay with this design and approach before I add other tests.

I also took the liberty of re-enabling a couple of older tests that I think were accidentally disabled: `Test_XPathDocument` and `Test_XPathDocument_NameTable` - both tests pass in all target frameworks without any modifications.

Here's the comparison: https://github.com/lovettchris/SgmlReader/compare/master...Jehoel:dev/201-06-whitespace?expand=1 

--------

Originally I was hoping/thinking that the `SgmlReader`'s node objects were _aware_ of their place in the SGML document, so that a Node "knows" if it's a self-closing element or not (based on the SGML DTD) _before_ the `InnerText` and `Value` properties are copied into an `XmlElement`, however I re-remembered that `SgmlReader` is strictly forward-only and when it builds-up the text string and encounters `<`  it has no way of knowing if it's automatically self-closing or not, that's only settled long afterwards.

...which was at-odds with how I wanted to avoid trailing whitespace from even existing in the first place - but I settled on a simpler approach that controls which overload of StringBuilder's `ToString()` is used, which at least does avoid unnecessary string copies at least.

**Comment by lovettchris** [comment]
Looks good, I turned it into a PR https://github.com/lovettchris/SgmlReader/pull/18 and left one comment about your change to the LoggingXmlReader, feel free to reply in the PR thread.

**Comment by lovettchris** [comment]
The convention is to set core.autocrlf=true on Windows.  Git itself stores everything as just \n, but when you set core.autocrlf=true git automagically converts everything to \r\n on your checked out files.  Then does the opposite when you commit and push so that what is in github is always just \n.  This is what I always do on windows.

**Comment by daiplusplus** [comment]
I saw you closed the PR just now - is there a blocking problem?

**Comment by lovettchris** [comment]
no just that you need to create the PR not me, so that I can add a code review.  I have a couple other comments.

**Comment by daiplusplus** [comment]
Yeah, that's weird - I don't know why GitHub doesn't make it easy to have "push-requests".

**Comment by lovettchris** [comment]
Resolve with PR https://github.com/lovettchris/SgmlReader/pull/19
