### ISSUE TITLE
Clarification request: can this project keep on using the `Microsoft.` NuGet packageId prefix?

### ISSUE THREAD

**Issue by daiplusplus** [lovettchris/SgmlReader#20]
As this isn't an official Microsoft project/product, won't this proejct get into trouble by publishing updates?

**Comment by lovettchris** [comment]
Good question, kind of up to Microsoft, will change it if needed.

**Comment by lg2de** [comment]
Hey @lovettchris.
I think it is quite confusing and misleading that the package is named "Microsoft" but not officially supported by MS.
We would be happy if you could rename assembly and package.
Do you think this can be completed soon?
