### ISSUE TITLE
Probably improper interpretation of inclusions and exclusions.

### ISSUE THREAD

**Issue by Demiurg-ls** [lovettchris/SgmlReader#45]
Hi,

There is probably an error in **Sgml.SgmlReader.ValidateContent(Node node)**

Elements are _"Element '{0}' not allowed inside '{1}', closing {2}."_ even if there are "active" inclusions in one of it's ancestors.
I've patched this (see attachement) but it could be done in better, more optimal way.

Best regards,

[SgmlReader - fix for misinterpreted dtd inclusions.zip](https://github.com/lovettchris/SgmlReader/files/9840771/SgmlReader.-.fix.for.misinterpreted.dtd.inclusions.zip)

**Comment by lovettchris** [comment]
Super cool, I'll checkout your proposed changes, thanks for doing this!

**Comment by Demiurg-ls** [comment]
You are welcome.
Thanks for the Library :)

**Comment by Demiurg-ls** [comment]
In the attachment you will find proposition of optimized changes - inclusions are verfified in the main loop.

Best regards

[SgmlReader - fix for misinterpreted dtd inclusions - optimized.zip](https://github.com/lovettchris/SgmlReader/files/9844089/SgmlReader.-.fix.for.misinterpreted.dtd.inclusions.-.optimized.zip)

**Comment by lovettchris** [comment]
Ok, I did a bunch of work on this and added some new tests to make sure inclusion/exclusion is working properly.  I also properly implemented general support for SGML optional start tags.  So when you parse html `<p>test</p>` you will get back the valid HTML document `<html><body><p>test</p></body></html>` and this works now for any SGML DTD and not just HTML.

**Comment by Demiurg-ls** [comment]
Hi, it is great that you are working on it.
I was planing to refernece your code again, but I think "inclusions" are not working properly yet.

As I can undestand SGML DTD inclusions (if not excluded):

`
< !ELEMENT root - - (childA|childB)* +(descendantA|descendantB)>
`

means that included elements are allowed **ANYWHERE** inside "root" - so "descendantA" can be a descendant of **ANY LEVEL** of "root". 
Current implementation allows included elements only in elements they are defined in.

for example for the definition above proper SGML could be:

`
<root>
  <descendantA />
  <childA><descendantA/></childA>
  <childB><descendantA><descendantA><descendantB></descendantA></descendantA></childB>
</root>
`

Best regards

**Comment by lovettchris** [comment]
Looking at http://sgmljs.net/docs/sgmlrefman.html it seems you are right, it says:

> inclusions is a single element or a name group (a list of elements) allowed to occur anywhere and arbitrarily often in descendant content in addition to elements specified in the content model

Implementing this efficiently will be a bit of a pain, I'll have to think about it.

**Comment by Demiurg-ls** [comment]
"[SgmlReader - fix for misinterpreted dtd inclusions - optimized.zip]"
Seems to work in case of big SGML files (300MB+)  that complains with quite complex iSpec2200 specification. There are inclusions used in its dtd.
I'm not sure it can be more optimized in a simple way. 

The strange thing is, that having aditional loop it is processing 333 165KB file in about 13,95s while current, git, version of library 15,58s (the result is wrong). I think it is due to processing errors and "autoclosing" tags. For proper sgml with no inclusions  git version would be faster I guess. 

Best regards
Łukasz Sokołowski

**Comment by lovettchris** [comment]
Ok, I pushed some fixes so include and exclude should inherit properly now.
See d5928270ef11838e64029119dde06da6eac8459f.
I also did some work to make sure this new implementation is more efficient.

**Comment by lovettchris** [comment]
Please reopen if you find any more bugs in this area, thanks.
