### ISSUE TITLE
Breaking change in 1.8.26 causes weird behavior when CaseFolding = None

### ISSUE THREAD

**Issue by kzu** [lovettchris/SgmlReader#48]
With 1.8.25, the following code:

```csharp
using System.Xml.Linq;
using Sgml;

var html =
    """
    <html>
    <head>
        <title>Hello</title>
    </head>
    <body>
        World
    </body>
    </html>
    """;

var reader = new SgmlReader
{
    DocType = "html",
    CaseFolding = CaseFolding.None,
    InputStream = new StringReader(html)
};

var doc = XDocument.Load(reader);
Console.WriteLine(doc.ToString());
```

Produced the following expected output:

```xml
<html>
<head>
    <title>Hello</title>
</head>
<body>
    World
</body>
</html>
```

Exact same code, with 1.8.26 containing a [case folding fix](https://github.com/lovettchris/SgmlReader/commit/65a1085889830cc8382c81b489c7ea2d44957e57) renders:

```xml
<HTML>
  <html>
<head>
    <title>Hello</title>
</head>
<body>
    World
</body>
</html>
</HTML>
```

I'm guessing the duplicate "auto-open/close" `HTML` element is being improperly added due to the non-case-insensitive check for a parent for `html` rather than `HTML`, or something like that.

So with 1.8.26+, effectively `CaseFolding.None` cannot be used :(

**Comment by lovettchris** [comment]
Thanks for the bug report, this is fixed in version https://www.nuget.org/packages/Microsoft.Xml.SgmlReader/1.8.29

**Comment by kzu** [comment]
Thanks a bunch!
