### ISSUE TITLE
Hangs reading wikipedia.org on every version after .26

### ISSUE THREAD

**Issue by kzu** [lovettchris/SgmlReader#51]
I have a basic santity check test for bumps of SgmlReader that just load wikipedia.org.

Since .27+, I haven't been able to bump since they all hang during the test run.

I have provided a full repro, which uses the exact same (linked) test file and only changes the referenced package version. You can open the main SgmlReader.sln and run the Version26..29 test projects and verify the hangs.

Hopefully this makes diagnosing it a bit easier 🙏 

Fork/branch: https://github.com/kzu/SgmlReader/tree/hang

Sent a PR to verify this is indeed the case in CI too.

**Comment by lovettchris** [comment]
Wow, terrible bug, thanks. It was yet another issue with case folding.  So I've decided to simplify dtd parsing and make the string comparisons of DTD names always case insensitive, independent of case folding. 
Fixed in https://www.nuget.org/packages/Microsoft.Xml.SgmlReader/1.8.30
