### ISSUE TITLE
Proposal: Package Nuget for All Xamarin Platforms

### ISSUE THREAD

**Issue by robloo** [lovettchris/SgmlReader#6]
This is a great project and is really valuable for the .net ecosystem.

I'm currently moving a UWP app cross-platform and this is one of the packages that Visual Studio is telling me isn't supported on Xamarin.Mac/iOS. I doubt there is anything in the code base preventing this from working in an AOT environment. However, instead of re-building this myself, I though perhaps we can make the Nuget package declare itself for Xamarin here in the repo. Would this be possible to do?

https://docs.microsoft.com/en-us/nuget/guides/create-packages-for-xamarin

**Comment by lovettchris** [comment]
That's odd, the nuget package contains binaries for .NETStandard2.0 and 2.1, these are supposed to be cross platform libraries.  You can even see in the article you referenced an example nuspec where they are saying the same thing with these cross platform libraries:

```xml
        <!-- Cross-platform reference assemblies -->
        <file src="Plugin.LoggingLibrary\bin\Release\Plugin.LoggingLibrary.dll" target="lib\netstandard1.4\Plugin.LoggingLibrary.dll" />
        <file src="Plugin.LoggingLibrary\bin\Release\Plugin.LoggingLibrary.xml" target="lib\netstandard1.4\Plugin.LoggingLibrary.xml" />
```

So I wonder why Xamarin is not allowing those SgmlReader libraries to be used on macOs and IOS?  Could it be that Xamarin only supports [older .NETStandard](https://forums.xamarin.com/discussion/117225/when-can-we-use-net-standard-2-0-for-xaamarin-forms-on-vs-mac) libraries?

**Comment by robloo** [comment]
I'm new to cross-platform development with .net so take everything I say with a grain of salt. That said, usually I expect Nuget to declare Xamarin support as below. The Xamarin info is listed separately even with .net standard 2.0.

![image](https://user-images.githubusercontent.com/17993847/93900900-f0fa9e00-fcc3-11ea-8307-78f689aef135.png)

Net standard 2.0 should be supported by all platforms though as you said. However, I'm getting the following error. I was mistaken and this is only for a certain enum though -- not the entire namespace.

![image](https://user-images.githubusercontent.com/17993847/93900776-c9a3d100-fcc3-11ea-8073-7341b36cbf6c.png)

I should add that I still don't have the solution building except for UWP so maybe this is one of those errors that disappears when a full build is completed.

**Comment by robloo** [comment]
Ok, so looking into this more, this does run fine on Xamarin Platforms -- my mistake. However, there are some incompatibilities with UWP/Xamarin code. Narrowing down the errors the problem is only here it seems:

`WhitespaceHandling = Sgml.WhitespaceHandling.Significant`

Changing this instead to the following works and is instead using the System.Xml.WhitespaceHandling enum.

`WhitespaceHandling = WhitespaceHandling.Significant`

This enum is defined as follows in the Sgml namespace - only for UWP. Assuming because in UWP there was no System.Xml originally. This [exists now though](https://docs.microsoft.com/en-us/dotnet/api/system.xml.whitespacehandling?view=netstandard-2.0) as of .net Standard 2.0.

```csharp

#if WINDOWS_UWP
    //
    // Summary:
    //     Specifies how white space is handled.
    //     (Not defined in PORTABLE framework, so we added it here).
    public enum WhitespaceHandling
    {
        //
        // Summary:
        //     Return Whitespace and SignificantWhitespace nodes. This is the default.
        All = 0,
        //
        // Summary:
        //     Return SignificantWhitespace nodes only.
        Significant = 1,
        //
        // Summary:
        //     Return no Whitespace and no SignificantWhitespace nodes.
        None = 2
    }
#endif
```

To avoid this trap in the future I think this enum should be fully removed from SgmlReader and instead always use what is in System.Xml?

**Comment by lovettchris** [comment]
I see, wow, thanks for debugging this, I'll push out a fix.

**Comment by robloo** [comment]
Awesome, thanks! Just note this is a breaking change for UWP only. I would guess there are very few using SgmlReader with UWP though.

**Comment by lovettchris** [comment]
Ok, I just pushed some fixes and published a new version 1.8.18.  I tested that a UWP app can call the SgmlReader to load resources, you have to remember to plug in the UniversalEntityResolver as follows:

```c#
        XmlDocument FromHtml(string url)
        {
            // setup SgmlReader
            SgmlReader sgmlReader = new SgmlReader()
            {
                DocType = "HTML",
                WhitespaceHandling = WhitespaceHandling.All,
                CaseFolding = CaseFolding.ToLower,
                Href = url,
                Resolver = new UniversalEntityResolver()
            };

            // create document
            XmlDocument doc = new XmlDocument()
            {
                PreserveWhitespace = true,
                XmlResolver = null
            };
            doc.Load(sgmlReader);
            return doc;
        }
```

Previously I was trying to build SgmlReaderDll in "UWP" mode and make the UniversalEntityResolver  automatic, but this new solution builds a new SgmlReaderCore.dll which is netstandard2.0 which UWP now supports.  But this separation means you need to plug in the UniversalEntityResolver manually.  I also added .pdb and .xml files in the nuget package for better debugging and intellisense.

**Comment by robloo** [comment]
Seems to work great and the types are now the same! Thanks so much for working on this 👍 

I'm not sure I understand the need for the UniversalEntityResolver() though. I'm using SgmlReader to convert OFX Sgml files into XML to parse using the same XML tooling as OFX Xml files. Really an amazing library for doing something like this. I'm guessing entity resolution wouldn't be needed in this case though and is HTML specific.

Also, the UniversalEntityResolver() is not available on Xamarin platforms -- so I would end up having to go back to #if conditional code to add it for UWP and remove it for Xamarin. Since my testing seems to indicate it's not needed in my case I'll remove the `Resolver = new UniversalEntityResolver()` line entirely.

**Comment by lovettchris** [comment]
Right UniversalEntityResolver was built mostly for older versions of UWP that did not allow System.IO API's to read files.  So you may not need UniversalEntityResolver, unless you find a resource that can only be loaded by Windows.Storage API's.
